name: real_time_chat_app
description: Real-Time Chat App

publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
